services:

  mongo:
    image: mongo:7.0-rc
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017
    container_name: newsletter-mongo

  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    ports:
      - 8081:8081
    depends_on:
      - mongo
    restart: always
    container_name: newsletter-mongo-express

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: newsletter-backend
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./data/backend:/application/data
    ports:
      - 8000:8000
    depends_on:
      - mongo
    container_name: newsletter-backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: newsletter-frontend
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    container_name: newsletter-frontend
